
import dynamic from 'next/dynamic';
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'


const MarkdownEditor = dynamic(() => import('../components/markdown'), { ssr: false });

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <MarkdownEditor />
      </main>
    </div>
  );
}

export default Home
